# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.trip_voter:
        class: AppBundle\Security\TripVoter
        tags:
            - { name: security.voter }
        public: false
    app.post_voter:
        class: AppBundle\Security\PostVoter
        tags:
            - { name: security.voter }
        public: false
    twig.extension.sortbyfield:
        class: Snilius\Twig\SortByFieldExtension
        tags:
            - { name: twig.extension }
    app.upload_listener:
        class: AppBundle\Event\UploadListener
        tags:
             - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
    app.picture_namer:
        class: AppBundle\PictureNamer